/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artmakesus_maxine_Maxine */

#ifndef _Included_com_artmakesus_maxine_Maxine
#define _Included_com_artmakesus_maxine_Maxine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artmakesus_maxine_Maxine
 * Method:    setTexturePixels
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_com_artmakesus_maxine_Maxine_setTexturePixels
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
